parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: false
env:
  browser: true
  node: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  shallow: true
  mount: true
  render: true

